name: Pull Request Approval Checklist
description: Ensure that your pull request fulfills all the requirements below for a smooth review process.
body:
  - type: markdown
    attributes:
      value: |
        # Pull Request Approval Checklist

        Thank you for your contribution! Please ensure that your PR fulfills all the requirements below to facilitate a smooth review process.

  - type: input
    id: pr_title
    attributes:
      label: PR Title
      description: Provide a concise title for your pull request.
      placeholder: Enter the PR title here...

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of your changes.
      placeholder: Describe what this PR does...

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: List any related issues (e.g., #123).
      placeholder: Mention related issues here...

  - type: checkboxes
    id: contribution_guidelines
    attributes:
      label: Contribution Guidelines
      description: Have you followed the contribution guidelines and adhered to the project's standards?
      options:
        - label: I have read and followed the contribution guidelines.

  - type: dropdown
    id: team_discussion
    attributes:
      label: Team Discussion
      description: Has this proposal been discussed and approved by the team?
      options:
        - Yes
        - No
        - Not Applicable

  - type: textarea
    id: problem_solution
    attributes:
      label: Problem and Solution
      description: Is the problem statement concise and does the solution directly address the problem? Describe how your solution addresses the problem.
      placeholder: Provide a brief description here...

  - type: dropdown
    id: architects_review
    attributes:
      label: Architect's Review
      description: Has the final solution been reviewed and approved by the architects?
      options:
        - Yes
        - No
        - Not Applicable

  - type: textarea
    id: design_review_board
    attributes:
      label: Design Review Board
      description: If applicable, include the agenda item from the design review board or link to the relevant task.
      placeholder: Include link or task ID here...

  - type: markdown
    attributes:
      value: |
        ## Checklist

        Please check all that apply:

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: My code follows the style guidelines of this project.
        - label: I have performed a self-review of my own code.
        - label: I have commented my code, particularly in hard-to-understand areas.
        - label: I have made corresponding changes to the documentation.
        - label: My changes generate no new warnings.
        - label: I have added tests that prove my fix is effective or that my feature works.
        - label: New and existing unit tests pass locally with my changes.

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Provide any additional information that might be helpful for reviewers.
      placeholder: Add any extra context, notes, or links here...
