name: "Bug Report"
description: "Report a bug"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Bug Report
        Please fill out the sections below to help us identify and fix the bug.
  - type: textarea
    id: description
    attributes:
      label: "Describe your issue"
      placeholder: "When I click here, this happens"
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: "Operating System"
      description: "What operating system are you using?"
      placeholder: "Example: macOS Big Sur"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: "Version"
      description: "What version of our software are you running?"
      multiple: false
      options:
        - 1.0.2 (Stable)
        - 1.0.3 (Beta)
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: "Checks before submitting the issue"
      description: "Please ensure the following checks have been made:"
      options:
        - label: "Validate X"
          required: true
        - label: "Checked Y"
          required: true
        - label: "Tried Z"
          required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "What was the expected result?"
      placeholder: "I expected this to happen"
  - type: textarea
    id: screenshots
    attributes:
      label: "Put here any screenshots or videos (optional)"
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
