# .github/workflows/ansible-lint.yml
name: Ansible linting action status

env:
  BRANCHES: '["main", "stable", "release/v*", "test*" ]'

on:
  push:
    branches:
      - "main"
      - "stable"
      - "release/v*"
      - "test*"
  pull_request:
    branches:
      - "main"
      - "stable"
      - "release/v*"
      - "test*"
  workflow_dispatch:
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
