# .github/workflows/ansible-lint.yml
name: ansible-lint

env:
  BRANCHES: '["main", "stable", "release/v*", "test*" ]'
  
on:
  push:
    branches: ${{ fromJson(env.BRANCHES ) }}
  pull_request:
    branches: ${{ fromJson(env.BRANCHES ) }}
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
