name: Auto Label New Issues

on:
  issues:
    types: [opened]

jobs:
  label-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to the new issue
        run: |
          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          curl -sSL -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"labels":["my-new-issue"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/labels"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
