# Add Web IDE link on PRs
name: web-ide

on:
  push:
    branches: "*"
  pull_request_target:
    # Add multiple activity types
    types: [opened, reopened, synchronize]

jobs:
  add-link:
    runs-on: ubuntu-20.04
    steps:
      - name: Web IDE Pull Request Check
        id: try-in-web-ide
        uses: redhat-actions/try-in-web-ide@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_comment: true
          add_status: true
permissions:
  checks: write
  contents: read
  pull-requests: write
